twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        app_title: easyamap
        mail_support: anthony@easyamap.fr
        version: 1.3.0
        portail: https://www.easyamap.fr